# Generated by Django 6.0.2 on 2026-03-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0009_campus_lead_preferred_campus_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
            ],
            options={
                'verbose_name': 'Correo Electronico',
                'verbose_name_plural': 'Correos Electronicos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.email',),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.lead',),
        ),
    ]
