# Generated by Django 6.0.2 on 2026-03-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Correo de Prospecto', 'verbose_name_plural': 'Correos de Prospectos'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Posible Cliente', 'verbose_name_plural': 'Posibles Clientes'},
        ),
    ]
