# Generated by Django 6.0.2 on 2026-03-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_email_options_alter_lead_options'),
        ('clients', '0009_campus_lead_preferred_campus_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
            },
        ),
        migrations.CreateModel(
            name='SocialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('x', 'X')], max_length=20)),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('author_handle', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('post_url', models.URLField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_messages', to='clients.lead')),
            ],
            options={
                'verbose_name': 'Mensaje Social',
                'verbose_name_plural': 'Social',
                'ordering': ('-received_at',),
            },
        ),
    ]
