# Generated by Django 6.0.2 on 2026-02-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_note_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted', models.BooleanField(default=False)),
            ],
        ),
    ]
