# Generated by Django 6.0.2 on 2026-03-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=50),
        ),
    ]
