# Generated by Django 6.0.2 on 2026-03-04 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_opportunity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Guatemala', max_length=100)),
                ('is_central', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clients.campus'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('site_type', models.CharField(choices=[('main', 'Sede principal'), ('subsite', 'Subsede')], default='main', max_length=20)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='clients.campus')),
            ],
            options={
                'unique_together': {('campus', 'name')},
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clients.site'),
        ),
    ]
