# Generated by Django 6.0.2 on 2026-03-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_highschool_socialmessage'),
        ('clients', '0009_campus_lead_preferred_campus_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='high_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='admissions.highschool'),
        ),
    ]
