# Generated by Codex on 2026-03-12

from django.db import migrations


def normalize_email_direction(apps, schema_editor):
    Email = apps.get_model("clients", "Email")
    Email.objects.filter(direction="out").update(direction="outbound")
    Email.objects.filter(direction="in").update(direction="inbound")


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_alter_email_options_alter_note_options_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_email_direction, migrations.RunPython.noop),
    ]
