# Generated by Django 6.0.2 on 2026-03-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
    ]
