# Generated by Django 6.0.2 on 2026-03-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0009_campus_lead_preferred_campus_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.client',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.note',),
        ),
    ]
