# Generated by Django 6.0.2 on 2026-03-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0009_campus_lead_preferred_campus_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.campus',),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.site',),
        ),
    ]
