# Generated by Django 6.0.2 on 2026-03-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0009_campus_lead_preferred_campus_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.opportunity',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.product',),
        ),
    ]
