# Generated by Django 6.0.2 on 2026-03-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicdegree_academicperiod_faculty'),
        ('clients', '0010_lead_high_school'),
        ('commercial', '0002_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('academic_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_offers', to='academics.academicdegree')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_offers', to='academics.academicperiod')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_offers', to='clients.campus')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_offers', to='academics.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_offers', to='commercial.product')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_offers', to='clients.site')),
            ],
            options={
                'verbose_name': 'Oferta Academica',
                'verbose_name_plural': 'Ofertas Academicas',
                'unique_together': {('program', 'campus', 'site', 'faculty', 'academic_degree', 'academic_period')},
            },
        ),
    ]
